update advance.yml

diff --git a/.github/workflows/advance.yml b/.github/workflows/advance.yml
--- a/.github/workflows/advance.yml
+++ b/.github/workflows/advance.yml
@@ -49,8 +49,30 @@ jobs:
         run: |
           eval $(opam env)
           make -skj$(nproc) ci
+          make -skj$(nproc) dist
+          # Did something change?
+          git add dist # must rest!
+          if ! git diff --quiet --cached dist; then
+            echo DISTCHANGE=1 >>$GITHUB_ENV
+          else
+            echo DISTCHANGE=0 >>$GITHUB_ENV
+          fi
+          git reset
 
-      - name: Push updated state
-        if: ${{ env.MOVED == '1' }}
+      - name: Push updated state, since there's no diff
+        if: ${{ env.MOVED == '1' && env.DISCHANGE == '0' }}
         run: |
+          # Use the token so we can push to these repos.
+          for dir in FStar karamel pulse; do
+            R=$(git remote get-url origin | grep -Eo '[[:alnum:]]*/[[:alnum:]]*$')
+            git remote set-url origin https://${{secrets.ADVANCE_GH_TOKEN}}@github.com/$R
+          done
           ./try-push.sh
+
+      - name: Make a PR! There's a diff to review.
+        if: ${{ env.MOVED == '1' && env.DISCHANGE == '1' }}
+        run:
+          # TODO, just fail for now.
+          exit 1
+          # git add . && git commit -m "Bump modules (dist changed)."
+          # gh pr create
