ci: add ciok job for branch protection

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -227,3 +227,18 @@ jobs:
           else
             echo "dist/ is up to date."
           fi
+
+  # Branch protection points here
+  ciok:
+    runs-on: ubuntu-latest
+    if: ${{ cancelled() || contains(needs.*.result, 'cancelled') || contains(needs.*.result, 'failure') }}
+    # ^ Workaround for insane github behavior: https://github.com/actions/runner/issues/2566
+    needs:
+      - verify
+      - test-and-bench
+      - bench-spmm
+      - check-dist
+    steps:
+      # Note: we only run on failure. Otherwise this is skipped, which counts
+      # as a success.
+      - run: exit 1
